# ここで実行したいRAGパイプラインの名前を指定するだけ
# active_pipeline: "graph_hybrid_combined_experiment"
# active_pipeline: "graph_rag_experiment"
# active_pipeline: "hybrid_search_experiment"
active_pipeline: "multi_query_experiment"
# active_pipeline: "raptor_experiment"
# active_pipeline: "self_rag_full_pipeline"
# active_pipeline: "structured_semantic_chunk-hyde_prf-chromadb_sentencetransformers-reranker-nli_filter"
# active_pipeline: "structured_semantic_chunk-hyde_prf-chromadb-gemini_embedding-reranker-nli_filter"